[theme]
primaryColor = "#0061A8"       # Azul oscuro corporativo
backgroundColor = "#FFFFFF"    # Fondo blanco puro
secondaryBackgroundColor = "#F0F2F6"  # Suave gris claro para paneles
textColor = "#0E1117"          # Gris muy oscuro para el texto
font = "sans serif"            # Tipografía neutra y profesional

[server]
headless = true
enableCORS = false
port = 8501

[browser]
gatherUsageStats = false
